language: c
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libtool
    - gperf
    - gcc-multilib
    - libgdbm-dev:i386
  coverity_scan:
    project:
      name: perl11/cperl
      description: a perl5 with classes, types, compilable, company friendly
    notification_email: rurban@cpan.org
    build_command_prepend: ./Configure -des -Dusedevel -Uversiononly -Dprefix=$HOME/cperl
    build_command: make -s -j4 ECHO=true
    branch_pattern: coverity
cache:
  apt: true
git:
  submodules: false
os:
- linux
- osx
branches:
  only:
  - master
  - /smoke/
  - /coverity/
  - /^maint-/
env:
  matrix:
  - CONFIGURE_OPTION='' XCC='gcc' XBITS=64
  - CONFIGURE_OPTION='-Duse64bitint' XCC="'gcc\ -m32'" XBITS=32
  - CONFIGURE_OPTION='-DDEBUGGING -Duseshrplib' XCC='clang'
  - CONFIGURE_OPTION='-Duse64bitall -Dusethreads -Duselongdouble' XCC='clang'
  - CONFIGURE_OPTION='-Dusethreads -DDEBUGGING -Duse64bitall -Dld=c++' XCC='c++'
  global:
    secure: t+N5w1yMOdTvDIu7g09ujEQ80Rz0p/hV+uYnoPBex0pSHJKAvEWqL/PltzTNaOwoh9BRjJiSCaO6Owbpib5skZw+kwx6G+jeMzI+m00VI2P2//xUasG2KaYH1CTu+o2BE16cmZFjDs1R2UKYuTg/2lzY0SoUuNYcAr7MDUnc6hdx/uC0B37vW//MlDb/I+3bi4Wjkg+zH2T2dWqcaKP9cL4O1Oa9ApEZgaQcSv26MmBrGJm0dKaorF5vVf1xkVe6lfKVPCepcI424wkEbmBfZs5I8FajYdWscEQ0KxYY9paWUA9/71uREhuu2tecN9sc2ym2PV5ycHn0igixwuWqMV69iTO+CW7bX+1mFdfMq/TsnhRhwGVTpt0aBTup9VOkjZAqtqcc4ziQ15R6sIrAorzz97v2oFXL+q5FPQuqtY4opw8QsrnjAmonoBjNIZau8mX1VAyBTOTJjfY2bZQXNqpxFoGAfQgDhDjA+EYiQ8dK8glBOPxlEWeCeOFgA/ddrTFSTMCbDd3f0dJIOs8aQHAGcIpKEI2/3DY2JNvotku5e1us16v3YSLJwaWV4pEh3UaGhVU74TrzfA4NiOaf54OXSjLJVuBrpEMyPwVHxF5NA3W7zj9vACxcexRQAu3ms0J6XOaGYZuk5jYkefVpUILdPuSqVhRIs7Y4LqzqAYA=
matrix:
  fast_finish: true
script:
- test -n $TRAVIS_TAG && CONFIGURE_OPTION="$CONFIGURE_OPTION -Dusedevel"; ./Configure
  -des -Uversiononly -Dcc="$XCC" $CONFIGURE_OPTION -Dprefix=$HOME/cperl/usr && make
  -j4 -s
- if [ ${TRAVIS_OS_NAME} = "linux" -o -z "`echo $CONFIGURE_OPTION | grep 'DDEBUGGING'
  2>/dev/null`" ]; then TEST_JOBS=4 make -s -j4 test_harness && make -s install &&
  $HOME/cperl/usr/bin/cperlivp -v -p; fi
before_deploy:
- if [ -z $CONFIGURE_OPTION -a test -n $XBITS ]; then tar -czvf cperl-${TRAVIS_TAG}-${TRAVIS_OS_NAME}${XBITS}.tar.gz
  -C $HOME/cperl *; fi
deploy:
  provider: releases
  file: cperl-${TRAVIS_TAG}-${TRAVIS_OS_NAME}${XBITS}.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  irc:
    channels:
    - irc.perl.org#perl11
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      %{build_url}'
