language: c
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libtool
  coverity_scan:
    project:
      name: "perl11/cperl"
      description: "a perl5 with classes, types, compilable, company friendly"
    notification_email: rurban@cpan.org
    build_command_prepend: "./Configure -des -Dusedevel -Dusecperl -Uversiononly -Dprefix=$HOME/perl-blead"
    build_command: "make -s -j4 ECHO=true"
    branch_pattern: coverity

cache:
  apt: true

os:
  - linux
  - osx

branches:
  only:
    - master
    - /bugfix/
    - /smoke/
    - /coverity/

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "PVpGzgkK+HYoVUE4LGE+uYs8G7q+xSIBfWnt+qVU7+5wx7WZX/ICEhyw2MId3UcRsATAKun92fJVPod8yJHF9NdnZ9ifUbzdimB1b46pAws+oqqWjyqfb59oT7ams6mXpd0+yXkH3PmJDUhM9L6K85uidzeJtYYH/4cKDqEMlLaI9eeOX28WySco0+ZRNHIwXIdluQeY2FOirSbTiqMGdKh3/k+dYrZwPkketcnkC6w1CYIVqD1StPjTzjkFkYGV7T6Yl63P8Oq9a1EPOL7NyycWc2uabuaiwaco30FmcW360al3SYgU07n1SKO854LeP239jexYhvTK7BEazVp+NCqHgSl9hzMkOaZ1ACP68jkq2EoNa/dltbSBc2VouvCTNYNWf8idqNvhmHdX3uP9S1Su3HbCThh2sb+IFQQCTqMZQOamQ2jcAW3EAgelV+2xbaFUPo3o6gIZnkwVaEwkWg1C+boX42gD3xWp4fU9SOqrsq/DOygBzkWNw0Z2JFK9mviLmnDDj0bil09PiNTOKc4MZMejgPo2iEUEXklbfwUOA3vHv3s0B+25WMiicM4UhRl1Jo/o3vkv79KSrms3ph0pEfnWYJ7vWz2i7YmBHwO7DHhVioSs30DVtVuAc4JE24mqRgk2Hhh1dsaEG80YBx/KkwLKXzKVmdjjjUJoEmI="
  matrix:
    - CONFIGURE_OPTION='' XCC='gcc'
    - CONFIGURE_OPTION='-DDEBUGGING' XCC='clang'
    - CONFIGURE_OPTION='-Duselongdouble' XCC='clang'
    - CONFIGURE_OPTION='-Duselongdouble -DDEBUGGING' XCC='gcc'
    - CONFIGURE_OPTION='-Duse64bitall -Dusethreads' XCC='gcc'
    - CONFIGURE_OPTION='-Dusethreads -DDEBUGGING -Duse64bitall' XCC='clang'
    - CONFIGURE_OPTION='-Ui_gdbm -Ut_gdbm' XCC="'gcc\ -m32'"

#-m32 mis-probes gdbm for 32bit. wrong probe, would need to download it from somewhere
# and of course Configure/metaconfig need to fix their library probes finally

matrix:
  allow_failures:
    - env: CONFIGURE_OPTION='-Ui_gdbm -Ut_gdbm' XCC="'gcc\ -m32'"
  fast_finish: true

#osx:   - CONFIGURE_OPTION='-Duselongdouble -Accflags="-march=corei7 -DPERL_FAKE_SIGNATURE"'
#linux: - CONFIGURE_OPTION='-Duselongdouble -Accflags="-march=native -msse4.2 -DPERL_FAKE_SIGNATURE"'

script:
  - ./Configure -des -Dusedevel -Uversiononly -Dcc="$XCC" $CONFIGURE_OPTION -Dprefix=$HOME/perl-blead && (make -j4 -s || true)
  - make -s
  - TEST_JOBS=4 make -s -j4 test_harness && make -s install && $HOME/perl-blead/bin/cperlivp

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
