language: c
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libtool
cache:
  apt: true

#-m32 misses gdbm for 32bit. wrong probe, would need to download it from somewhere

os:
  - linux
  - osx

branches:
  except:
    - branch-point
    - /^type(sd)/
    - /-v5.22.0$/

env:
  matrix:
    - CONFIGURE_OPTION='' CC='gcc'
    - CONFIGURE_OPTION='-DDEBUGGING' CC='clang'
    - CONFIGURE_OPTION='-Duselongdouble' CC='clang'
    - CONFIGURE_OPTION='-Duselongdouble -DDEBUGGING' CC='gcc'
    - CONFIGURE_OPTION='-Duse64bitall -Dusethreads' CC='gcc'
    - CONFIGURE_OPTION='-Duse64bitall -Dusethreads -DDEBUGGING' CC='clang'

#   - CONFIGURE_OPTION='-Duselongdouble -Accflags="-march=native"'

script:
  - ./Configure -des -Dusedevel -Dusecperl -Uversiononly -Dcc=$CC $CONFIGURE_OPTION -Dprefix=$HOME/perl-blead && (make -j4 -s || make -s configpm || true)
  - make -s || make -s mini_post || true
  - TEST_JOBS=4 make -s -j4 test_harness && make -s install && $HOME/perl-blead/bin/cperlivp

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
